set-option -g window-size smallest
set -g mouse on

# Enable extended keys support in tmux
set -s extended-keys on
# Tell tmux that your terminal features support extended keys
set -as terminal-features 'xterm*:extkeys'
# Explicitly bind Shift+Enter to send the standard CSI u sequence for newline
bind -n S-Enter send-keys -H 1b 5b 31 33 3b 32 75

# Enable pane navigation using Alt + Arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
